;;; kanagawa-dragon-nvim-theme.el --- Faithful port of nvim's Kanagawa-Dragon -*- lexical-binding: t; -*-

;; Copyright (C) 2026 Brandon Larocque
;; Author: Brandon Larocque
;; Version: 0.1.2
;; Package-Requires: ((emacs "29.1"))
;; Keywords: faces, theme
;; URL: https://github.com/bdkl/kanagawa-dragon-nvim-emacs
;; SPDX-License-Identifier: MIT

;;; Commentary:

;; Faithful Emacs port of the Dragon variant of `kanagawa.nvim'
;; (https://github.com/rebelot/kanagawa.nvim) by rebelot.  Independent
;; project; not affiliated with upstream.
;;
;; Goals (see spec.md for the full contract):
;;
;;   1. Side-by-side a Java buffer in Doom Emacs (this theme) and the
;;      same buffer in nvim with `kanagawa-dragon' should feel like the
;;      same theme.
;;   2. Vanilla `deftheme' — no `doom-themes' macro dependency.
;;   3. Treesit-correct: every Emacs 29+ `font-lock-*' face introduced
;;      for tree-sitter is mapped, so Java/Python/Rust at
;;      `treesit-font-lock-level' 4 don't collapse to a single fg.
;;
;; Doom-specific faces (`doom-modeline-*', `solaire-*', etc.) are mapped
;; as no-op specifications when those packages are absent — vanilla
;; Emacs loads the theme cleanly.

;;; Code:

(require 'kanagawa-dragon-nvim)

(deftheme kanagawa-dragon-nvim
  "Faithful port of nvim's Kanagawa-Dragon.")

(let* ((p kanagawa-dragon-nvim-palette)
       (c (lambda (name) (cdr (assq name p))))
       ;; UI
       (bg          (funcall c 'dragonBlack3))
       (bg-dim      (funcall c 'dragonBlack1))
       (bg-m3       (funcall c 'dragonBlack0))
       (bg-m2       (funcall c 'dragonBlack1))
       (bg-m1       (funcall c 'dragonBlack2))
       (bg-p1       (funcall c 'dragonBlack4))
       (bg-p2       (funcall c 'dragonBlack5))
       (bg-gutter   (funcall c 'dragonBlack4))
       (bg-visual   (funcall c 'waveBlue1))
       (bg-search   (funcall c 'waveBlue2))
       (bg-float    (funcall c 'dragonBlack0))
       (border      (funcall c 'sumiInk6))
       (fg          (funcall c 'dragonWhite))
       (fg-dim      (funcall c 'oldWhite))
       (special     (funcall c 'dragonGray3))
       (whitespace  (funcall c 'dragonBlack6))
       (nontext     (funcall c 'dragonBlack6))
       ;; Syntax
       (s-string    (funcall c 'dragonGreen2))
       (s-number    (funcall c 'dragonPink))
       (s-constant  (funcall c 'dragonOrange))
       (s-ident     (funcall c 'dragonYellow))
       (s-param     (funcall c 'dragonGray))
       (s-fun       (funcall c 'dragonBlue2))
       (s-statement (funcall c 'dragonViolet))
       (s-keyword   (funcall c 'dragonViolet))
       (s-operator  (funcall c 'dragonRed))
       (s-preproc   (funcall c 'dragonRed))
       (s-type      (funcall c 'dragonAqua))
       (s-regex     (funcall c 'dragonRed))
       (s-deprec    (funcall c 'katanaGray))
       (s-punct     (funcall c 'dragonGray2))
       (s-comment   (funcall c 'dragonAsh))
       (s-special1  (funcall c 'dragonTeal))
       (s-special2  (funcall c 'dragonRed))
       (s-special3  (funcall c 'dragonRed))
       ;; Diagnostics
       (d-error     (funcall c 'samuraiRed))
       (d-warn      (funcall c 'roninYellow))
       (d-info      (funcall c 'dragonBlue))
       (d-ok        (funcall c 'springGreen))
       ;; Diff (backgrounds)
       (diff-add-bg    (funcall c 'winterGreen))
       (diff-del-bg    (funcall c 'winterRed))
       (diff-chg-bg    (funcall c 'winterBlue))
       (diff-text-bg   (funcall c 'winterYellow))
       ;; VCS (foregrounds for gutter / status)
       (vcs-add     (funcall c 'autumnGreen))
       (vcs-del     (funcall c 'autumnRed))
       (vcs-chg     (funcall c 'autumnYellow))
       ;; ANSI (Dragon term[1..18] from upstream)
       (ansi-black          (funcall c 'dragonBlack0))
       (ansi-red            (funcall c 'dragonRed))
       (ansi-green          (funcall c 'dragonGreen2))
       (ansi-yellow         (funcall c 'dragonYellow))
       (ansi-blue           (funcall c 'dragonBlue2))
       (ansi-magenta        (funcall c 'dragonPink))
       (ansi-cyan           (funcall c 'dragonAqua))
       (ansi-white          (funcall c 'oldWhite))
       (ansi-bright-black   (funcall c 'dragonGray))
       (ansi-bright-red     (funcall c 'waveRed))
       (ansi-bright-green   (funcall c 'dragonGreen))
       (ansi-bright-yellow  (funcall c 'carpYellow))
       (ansi-bright-blue    (funcall c 'springBlue))
       (ansi-bright-magenta (funcall c 'springViolet1))
       (ansi-bright-cyan    (funcall c 'waveAqua2))
       (ansi-bright-white   (funcall c 'dragonWhite)))

  (custom-theme-set-faces
   'kanagawa-dragon-nvim

   ;; ----------------------------------------------------------------
   ;; Phase 2 — Core UI
   ;; ----------------------------------------------------------------
   `(default                ((t (:background ,bg :foreground ,fg))))
   `(cursor                 ((t (:background ,fg))))
   `(region                 ((t (:background ,bg-visual :extend t))))
   `(secondary-selection    ((t (:background ,bg-search :extend t))))
   `(highlight              ((t (:background ,bg-p1 :foreground ,fg))))
   `(hl-line                ((t (:background ,bg-gutter :extend t))))
   `(fringe                 ((t (:background ,bg :foreground ,nontext))))
   `(line-number            ((t (:background ,bg :foreground ,bg-p2))))
   `(line-number-current-line ((t (:background ,bg-gutter :foreground ,fg :weight bold))))
   `(line-number-major-tick ((t (:foreground ,fg-dim))))
   `(line-number-minor-tick ((t (:foreground ,whitespace))))
   `(vertical-border        ((t (:foreground ,bg-p1))))
   `(window-divider         ((t (:foreground ,bg-p1))))
   `(window-divider-first-pixel ((t (:foreground ,bg-p1))))
   `(window-divider-last-pixel  ((t (:foreground ,bg-p1))))
   `(internal-border        ((t (:background ,bg))))
   `(child-frame-border     ((t (:background ,border))))
   `(border                 ((t (:background ,bg :foreground ,border))))
   `(match                  ((t (:background ,bg-search :foreground ,fg :weight bold))))
   `(isearch                ((t (:background ,bg-search :foreground ,fg :weight bold))))
   `(isearch-fail           ((t (:background ,diff-del-bg :foreground ,d-error))))
   `(lazy-highlight         ((t (:background ,bg-visual :foreground ,fg))))
   `(query-replace          ((t (:background ,s-special2 :foreground ,bg))))
   `(trailing-whitespace    ((t (:background ,diff-del-bg))))
   `(whitespace-trailing    ((t (:background ,diff-del-bg))))
   `(whitespace-line        ((t (:background ,bg-m1))))
   `(whitespace-tab         ((t (:foreground ,whitespace))))
   `(whitespace-space       ((t (:foreground ,whitespace))))
   `(whitespace-newline     ((t (:foreground ,whitespace))))
   `(escape-glyph           ((t (:foreground ,s-special2))))
   `(homoglyph              ((t (:foreground ,s-special1))))
   `(shadow                 ((t (:foreground ,fg-dim))))
   `(success                ((t (:foreground ,d-ok))))
   `(warning                ((t (:foreground ,d-warn))))
   `(error                  ((t (:foreground ,d-error))))
   `(link                   ((t (:foreground ,s-fun :underline t))))
   `(link-visited           ((t (:foreground ,s-statement :underline t))))
   `(custom-link            ((t (:foreground ,s-fun :underline t))))
   `(button                 ((t (:foreground ,s-fun :underline t))))
   `(header-line            ((t (:background ,bg-m1 :foreground ,fg))))
   `(mode-line              ((t (:background ,bg-m1 :foreground ,fg))))
   `(mode-line-inactive     ((t (:background ,bg-m2 :foreground ,fg-dim))))
   `(mode-line-active       ((t (:inherit mode-line))))
   `(mode-line-highlight    ((t (:foreground ,s-fun))))
   `(mode-line-buffer-id    ((t (:foreground ,s-type :weight bold))))
   `(minibuffer-prompt      ((t (:foreground ,s-keyword :weight bold))))
   `(tooltip                ((t (:background ,bg-float :foreground ,fg))))
   `(menu                   ((t (:background ,bg-float :foreground ,fg))))
   `(fill-column-indicator  ((t (:foreground ,bg-p1))))

   ;; show-paren / smartparens
   `(show-paren-match       ((t (:background ,s-special1 :foreground ,bg :weight bold))))
   `(show-paren-match-expression ((t (:background ,bg-p1))))
   `(show-paren-mismatch    ((t (:background ,d-error :foreground ,bg :weight bold))))
   `(sp-show-pair-match-face ((t (:inherit show-paren-match))))
   `(sp-show-pair-mismatch-face ((t (:inherit show-paren-mismatch))))

   ;; ----------------------------------------------------------------
   ;; Phase 3 + 4 — Syntax (font-lock + treesit additions)
   ;; ----------------------------------------------------------------
   `(font-lock-comment-face            ((t (:foreground ,s-comment :slant italic))))
   `(font-lock-comment-delimiter-face  ((t (:foreground ,s-comment :slant italic))))
   `(font-lock-doc-face                ((t (:foreground ,s-comment :slant italic))))
   `(font-lock-doc-markup-face         ((t (:foreground ,special))))
   `(font-lock-string-face             ((t (:foreground ,s-string))))
   `(font-lock-keyword-face            ((t (:foreground ,s-keyword :slant italic))))
   `(font-lock-builtin-face            ((t (:foreground ,s-statement :slant italic))))
   `(font-lock-constant-face           ((t (:foreground ,s-constant))))
   `(font-lock-number-face             ((t (:foreground ,s-number))))
   `(font-lock-type-face               ((t (:foreground ,s-type))))
   `(font-lock-function-name-face      ((t (:foreground ,s-fun))))
   `(font-lock-function-call-face      ((t (:foreground ,s-fun))))
   `(font-lock-variable-name-face      ((t (:foreground ,s-ident))))
   `(font-lock-variable-use-face       ((t (:foreground ,s-param))))
   `(font-lock-property-name-face      ((t (:foreground ,s-ident))))
   `(font-lock-property-use-face       ((t (:foreground ,s-ident))))
   `(font-lock-operator-face           ((t (:foreground ,s-operator))))
   `(font-lock-preprocessor-face       ((t (:foreground ,s-preproc))))
   `(font-lock-regexp-face             ((t (:foreground ,s-regex))))
   `(font-lock-regexp-grouping-backslash ((t (:foreground ,s-regex))))
   `(font-lock-regexp-grouping-construct ((t (:foreground ,s-regex))))
   `(font-lock-bracket-face            ((t (:foreground ,s-punct))))
   `(font-lock-delimiter-face          ((t (:foreground ,s-punct))))
   `(font-lock-punctuation-face        ((t (:foreground ,s-punct))))
   `(font-lock-misc-punctuation-face   ((t (:foreground ,s-punct))))
   `(font-lock-escape-face             ((t (:foreground ,s-special2))))
   `(font-lock-negation-char-face      ((t (:foreground ,s-special3))))
   `(font-lock-warning-face            ((t (:foreground ,d-warn :weight bold))))

   ;; tree-sitter (elisp-tree-sitter package; distinct face namespace)
   `(tree-sitter-hl-face:attribute     ((t (:foreground ,s-constant))))
   `(tree-sitter-hl-face:comment       ((t (:inherit font-lock-comment-face))))
   `(tree-sitter-hl-face:constant      ((t (:foreground ,s-constant))))
   `(tree-sitter-hl-face:constant.builtin ((t (:foreground ,s-constant :weight semi-bold))))
   `(tree-sitter-hl-face:constructor   ((t (:foreground ,s-type))))
   `(tree-sitter-hl-face:escape        ((t (:foreground ,s-special2))))
   `(tree-sitter-hl-face:function      ((t (:foreground ,s-fun))))
   `(tree-sitter-hl-face:function.builtin ((t (:foreground ,s-fun :weight semi-bold))))
   `(tree-sitter-hl-face:function.call ((t (:foreground ,s-fun))))
   `(tree-sitter-hl-face:function.macro ((t (:foreground ,s-preproc))))
   `(tree-sitter-hl-face:function.special ((t (:foreground ,s-special1))))
   `(tree-sitter-hl-face:keyword       ((t (:foreground ,s-keyword))))
   `(tree-sitter-hl-face:label         ((t (:foreground ,s-special1))))
   `(tree-sitter-hl-face:method        ((t (:foreground ,s-fun))))
   `(tree-sitter-hl-face:method.call   ((t (:foreground ,s-fun))))
   `(tree-sitter-hl-face:number        ((t (:foreground ,s-number))))
   `(tree-sitter-hl-face:operator      ((t (:foreground ,s-operator))))
   `(tree-sitter-hl-face:property      ((t (:foreground ,s-ident))))
   `(tree-sitter-hl-face:property.definition ((t (:foreground ,s-ident))))
   `(tree-sitter-hl-face:punctuation   ((t (:foreground ,s-punct))))
   `(tree-sitter-hl-face:punctuation.bracket ((t (:foreground ,s-punct))))
   `(tree-sitter-hl-face:punctuation.delimiter ((t (:foreground ,s-punct))))
   `(tree-sitter-hl-face:punctuation.special ((t (:foreground ,s-special2))))
   `(tree-sitter-hl-face:string        ((t (:foreground ,s-string))))
   `(tree-sitter-hl-face:string.special ((t (:foreground ,s-special2))))
   `(tree-sitter-hl-face:tag           ((t (:foreground ,s-keyword))))
   `(tree-sitter-hl-face:type          ((t (:foreground ,s-type))))
   `(tree-sitter-hl-face:type.argument ((t (:foreground ,s-param))))
   `(tree-sitter-hl-face:type.builtin  ((t (:foreground ,s-type :weight semi-bold))))
   `(tree-sitter-hl-face:type.parameter ((t (:foreground ,s-param))))
   `(tree-sitter-hl-face:variable      ((t (:foreground ,s-ident))))
   `(tree-sitter-hl-face:variable.builtin ((t (:foreground ,s-special2 :slant italic))))
   `(tree-sitter-hl-face:variable.parameter ((t (:foreground ,s-param))))
   `(tree-sitter-hl-face:variable.special ((t (:foreground ,s-special2))))

   ;; ----------------------------------------------------------------
   ;; Diff / VCS
   ;; ----------------------------------------------------------------
   `(diff-added             ((t (:background ,diff-add-bg :foreground ,vcs-add :extend t))))
   `(diff-removed           ((t (:background ,diff-del-bg :foreground ,vcs-del :extend t))))
   `(diff-changed           ((t (:background ,diff-chg-bg :foreground ,vcs-chg :extend t))))
   `(diff-refine-added      ((t (:background ,diff-add-bg :foreground ,fg))))
   `(diff-refine-removed    ((t (:background ,diff-del-bg :foreground ,fg))))
   `(diff-refine-changed    ((t (:background ,diff-text-bg :foreground ,fg))))
   `(diff-header            ((t (:background ,bg-m1 :foreground ,fg :weight bold))))
   `(diff-file-header       ((t (:background ,bg-m1 :foreground ,s-fun :weight bold))))
   `(diff-hunk-header       ((t (:background ,bg-m1 :foreground ,s-keyword))))

   `(diff-hl-insert         ((t (:foreground ,vcs-add :background ,diff-add-bg))))
   `(diff-hl-delete         ((t (:foreground ,vcs-del :background ,diff-del-bg))))
   `(diff-hl-change         ((t (:foreground ,vcs-chg :background ,diff-chg-bg))))
   `(diff-hl-margin-insert  ((t (:foreground ,vcs-add :background ,bg-gutter))))
   `(diff-hl-margin-delete  ((t (:foreground ,vcs-del :background ,bg-gutter))))
   `(diff-hl-margin-change  ((t (:foreground ,vcs-chg :background ,bg-gutter))))

   `(git-gutter:added       ((t (:foreground ,vcs-add :background ,bg-gutter))))
   `(git-gutter:deleted     ((t (:foreground ,vcs-del :background ,bg-gutter))))
   `(git-gutter:modified    ((t (:foreground ,vcs-chg :background ,bg-gutter))))
   `(git-gutter-fr:added    ((t (:foreground ,vcs-add))))
   `(git-gutter-fr:deleted  ((t (:foreground ,vcs-del))))
   `(git-gutter-fr:modified ((t (:foreground ,vcs-chg))))

   ;; ----------------------------------------------------------------
   ;; Phase 5 — Doom-specific UI (no-op in vanilla Emacs)
   ;; ----------------------------------------------------------------
   `(solaire-default-face       ((t (:background ,bg-m1 :foreground ,fg))))
   `(solaire-fringe-face        ((t (:background ,bg-m1))))
   `(solaire-line-number-face   ((t (:background ,bg-m1 :foreground ,bg-p2))))
   `(solaire-hl-line-face       ((t (:background ,bg-gutter :extend t))))
   `(solaire-mode-line-face     ((t (:background ,bg-m3 :foreground ,fg))))
   `(solaire-mode-line-inactive-face ((t (:background ,bg-m2 :foreground ,fg-dim))))
   `(solaire-header-line-face   ((t (:background ,bg-m1 :foreground ,fg))))
   `(solaire-org-hide-face      ((t (:foreground ,bg))))

   `(doom-modeline              ((t (:inherit mode-line))))
   `(doom-modeline-bar          ((t (:background ,s-keyword))))
   `(doom-modeline-bar-inactive ((t (:background ,bg-m2))))
   `(doom-modeline-buffer-path  ((t (:foreground ,s-type :weight bold))))
   `(doom-modeline-buffer-file  ((t (:foreground ,s-type :weight bold))))
   `(doom-modeline-buffer-modified ((t (:foreground ,s-constant :weight bold))))
   `(doom-modeline-buffer-major-mode ((t (:foreground ,s-fun :weight bold))))
   `(doom-modeline-buffer-minor-mode ((t (:foreground ,fg-dim))))
   `(doom-modeline-project-dir  ((t (:foreground ,s-fun :weight bold))))
   `(doom-modeline-project-root-dir ((t (:foreground ,s-fun))))
   `(doom-modeline-project-parent-dir ((t (:foreground ,fg-dim))))
   `(doom-modeline-info         ((t (:foreground ,s-string))))
   `(doom-modeline-warning      ((t (:foreground ,d-warn))))
   `(doom-modeline-urgent       ((t (:foreground ,d-error))))
   `(doom-modeline-debug        ((t (:foreground ,fg-dim))))
   `(doom-modeline-error        ((t (:foreground ,d-error))))
   `(doom-modeline-highlight    ((t (:foreground ,s-fun))))
   `(doom-modeline-host         ((t (:foreground ,s-special1 :slant italic))))
   `(doom-modeline-input-method ((t (:foreground ,s-statement))))
   `(doom-modeline-panel        ((t (:background ,s-fun :foreground ,bg :weight bold))))
   `(doom-modeline-lsp-success  ((t (:foreground ,d-ok))))
   `(doom-modeline-lsp-warning  ((t (:foreground ,d-warn))))
   `(doom-modeline-lsp-error    ((t (:foreground ,d-error))))
   `(doom-modeline-lsp-running  ((t (:foreground ,s-statement))))
   `(doom-modeline-battery-charging ((t (:foreground ,d-ok))))
   `(doom-modeline-battery-full ((t (:foreground ,s-type))))
   `(doom-modeline-battery-normal ((t (:foreground ,fg))))
   `(doom-modeline-battery-warning ((t (:foreground ,d-warn))))
   `(doom-modeline-battery-critical ((t (:foreground ,d-error))))
   `(doom-modeline-battery-error ((t (:foreground ,d-error))))
   `(doom-modeline-evil-emacs-state    ((t (:foreground ,s-fun))))
   `(doom-modeline-evil-insert-state   ((t (:foreground ,s-string))))
   `(doom-modeline-evil-motion-state   ((t (:foreground ,s-special1))))
   `(doom-modeline-evil-normal-state   ((t (:foreground ,s-type))))
   `(doom-modeline-evil-operator-state ((t (:foreground ,s-fun))))
   `(doom-modeline-evil-replace-state  ((t (:foreground ,s-operator))))
   `(doom-modeline-evil-visual-state   ((t (:foreground ,s-constant))))

   `(doom-themes-visual-bell    ((t (:background ,d-error))))

   `(doom-dashboard-banner            ((t (:foreground ,s-keyword :weight bold))))
   `(doom-dashboard-footer            ((t (:foreground ,fg-dim))))
   `(doom-dashboard-footer-icon       ((t (:foreground ,s-keyword))))
   `(doom-dashboard-loaded            ((t (:foreground ,d-ok))))
   `(doom-dashboard-menu-desc         ((t (:foreground ,fg))))
   `(doom-dashboard-menu-title        ((t (:foreground ,s-fun :weight bold))))

   ;; vc-gutter (Doom +pretty)
   `(vc-edited-state        ((t (:foreground ,vcs-chg))))
   `(vc-locally-added-state ((t (:foreground ,vcs-add))))
   `(vc-removed-state       ((t (:foreground ,vcs-del))))

   ;; Tabs
   `(tab-line               ((t (:background ,bg-m1 :foreground ,fg-dim))))
   `(tab-line-tab           ((t (:background ,bg-m1 :foreground ,fg))))
   `(tab-line-tab-current   ((t (:background ,bg :foreground ,fg :weight bold))))
   `(tab-line-tab-inactive  ((t (:background ,bg-m1 :foreground ,fg-dim))))
   `(tab-line-highlight     ((t (:background ,bg :foreground ,fg))))
   `(tab-bar                ((t (:background ,bg-m1 :foreground ,fg))))
   `(tab-bar-tab            ((t (:background ,bg :foreground ,fg :weight bold))))
   `(tab-bar-tab-inactive   ((t (:background ,bg-m1 :foreground ,fg-dim))))

   ;; centaur-tabs
   `(centaur-tabs-default              ((t (:background ,bg-m1))))
   `(centaur-tabs-selected             ((t (:background ,bg :foreground ,fg :weight bold))))
   `(centaur-tabs-unselected           ((t (:background ,bg-m1 :foreground ,fg-dim))))
   `(centaur-tabs-selected-modified    ((t (:background ,bg :foreground ,s-constant :weight bold))))
   `(centaur-tabs-unselected-modified  ((t (:background ,bg-m1 :foreground ,s-constant))))
   `(centaur-tabs-active-bar-face      ((t (:background ,s-keyword))))

   ;; ----------------------------------------------------------------
   ;; Phase 6 — Org / org-modern
   ;; ----------------------------------------------------------------
   `(org-level-1            ((t (:foreground ,s-keyword :weight bold))))
   `(org-level-2            ((t (:foreground ,s-fun :weight bold))))
   `(org-level-3            ((t (:foreground ,s-type :weight bold))))
   `(org-level-4            ((t (:foreground ,s-string :weight bold))))
   `(org-level-5            ((t (:foreground ,s-ident))))
   `(org-level-6            ((t (:foreground ,s-constant))))
   `(org-level-7            ((t (:foreground ,s-number))))
   `(org-level-8            ((t (:foreground ,s-operator))))
   `(org-document-title     ((t (:foreground ,s-keyword :weight bold :height 1.2))))
   `(org-document-info      ((t (:foreground ,fg-dim))))
   `(org-document-info-keyword ((t (:foreground ,s-comment))))
   `(org-meta-line          ((t (:foreground ,s-comment))))
   `(org-block              ((t (:background ,bg-dim :extend t))))
   `(org-block-begin-line   ((t (:background ,bg-m1 :foreground ,s-comment :extend t))))
   `(org-block-end-line     ((t (:background ,bg-m1 :foreground ,s-comment :extend t))))
   `(org-quote              ((t (:background ,bg-dim :slant italic :extend t))))
   `(org-verbatim           ((t (:foreground ,s-string))))
   `(org-code               ((t (:background ,bg-dim :foreground ,s-fun))))
   `(org-formula            ((t (:foreground ,s-operator))))
   `(org-todo               ((t (:foreground ,s-constant :weight bold))))
   `(org-done               ((t (:foreground ,s-comment :weight bold))))
   `(org-headline-todo      ((t (:foreground ,fg))))
   `(org-headline-done      ((t (:foreground ,s-comment :strike-through t))))
   `(org-priority           ((t (:foreground ,s-operator :weight bold))))
   `(org-tag                ((t (:foreground ,s-special1 :weight bold))))
   `(org-special-keyword    ((t (:foreground ,s-comment))))
   `(org-date               ((t (:foreground ,s-type :underline t))))
   `(org-link               ((t (:foreground ,s-fun :underline t))))
   `(org-footnote           ((t (:foreground ,s-special1))))
   `(org-footnote-link      ((t (:foreground ,s-fun :underline t))))
   `(org-checkbox           ((t (:foreground ,s-fun :weight bold))))
   `(org-table              ((t (:foreground ,fg :background ,bg-dim))))
   `(org-table-header       ((t (:foreground ,s-keyword :background ,bg-m1 :weight bold))))
   `(org-ellipsis           ((t (:foreground ,s-comment :underline nil))))
   `(org-hide               ((t (:foreground ,bg))))
   `(org-indent             ((t (:foreground ,bg :background ,bg))))
   `(org-agenda-date        ((t (:foreground ,s-type :weight bold))))
   `(org-agenda-date-today  ((t (:foreground ,s-keyword :weight bold :underline t))))
   `(org-agenda-date-weekend ((t (:foreground ,s-fun))))
   `(org-agenda-structure   ((t (:foreground ,s-keyword :weight bold))))
   `(org-agenda-current-time ((t (:foreground ,s-constant :weight bold))))
   `(org-agenda-done        ((t (:foreground ,s-comment))))
   `(org-scheduled          ((t (:foreground ,s-string))))
   `(org-scheduled-today    ((t (:foreground ,s-fun))))
   `(org-scheduled-previously ((t (:foreground ,s-operator))))
   `(org-upcoming-deadline  ((t (:foreground ,s-operator))))
   `(org-upcoming-distant-deadline ((t (:foreground ,fg-dim))))
   `(org-warning            ((t (:foreground ,d-warn :weight bold))))

   `(org-modern-tag         ((t (:foreground ,s-special1 :background ,bg-m1 :weight bold))))
   `(org-modern-todo        ((t (:foreground ,s-constant :background ,bg-m1 :weight bold))))
   `(org-modern-done        ((t (:foreground ,s-comment :background ,bg-m1))))
   `(org-modern-date-active ((t (:foreground ,bg :background ,s-type))))
   `(org-modern-date-inactive ((t (:foreground ,fg-dim :background ,bg-m1))))
   `(org-modern-time-active ((t (:foreground ,bg :background ,s-keyword))))
   `(org-modern-time-inactive ((t (:foreground ,fg-dim :background ,bg-m1))))
   `(org-modern-block-name  ((t (:foreground ,s-comment))))
   `(org-modern-label       ((t (:background ,bg-m1))))

   ;; ----------------------------------------------------------------
   ;; Phase 7 — Completion stack
   ;; ----------------------------------------------------------------
   `(vertico-current        ((t (:background ,bg-visual :foreground ,fg :weight bold))))
   `(vertico-multiline      ((t (:foreground ,fg-dim))))
   `(vertico-group-title    ((t (:foreground ,s-keyword :weight bold))))
   `(vertico-group-separator ((t (:foreground ,s-comment :strike-through t))))

   `(vertico-posframe       ((t (:background ,bg-float :foreground ,fg))))
   `(vertico-posframe-border ((t (:background ,border))))

   `(corfu-default          ((t (:background ,bg-float :foreground ,fg))))
   `(corfu-current          ((t (:background ,bg-visual :foreground ,fg :weight bold))))
   `(corfu-bar              ((t (:background ,s-keyword))))
   `(corfu-border           ((t (:background ,border))))
   `(corfu-annotations      ((t (:foreground ,s-comment))))
   `(corfu-deprecated       ((t (:foreground ,s-deprec :strike-through t))))
   `(corfu-echo             ((t (:foreground ,s-comment))))

   `(orderless-match-face-0 ((t (:foreground ,s-fun :weight bold))))
   `(orderless-match-face-1 ((t (:foreground ,s-string :weight bold))))
   `(orderless-match-face-2 ((t (:foreground ,s-type :weight bold))))
   `(orderless-match-face-3 ((t (:foreground ,s-constant :weight bold))))

   `(marginalia-key         ((t (:foreground ,s-fun))))
   `(marginalia-documentation ((t (:foreground ,s-comment :slant italic))))
   `(marginalia-file-name   ((t (:foreground ,fg))))
   `(marginalia-file-priv-dir ((t (:foreground ,s-fun))))
   `(marginalia-file-priv-read ((t (:foreground ,s-string))))
   `(marginalia-file-priv-write ((t (:foreground ,s-constant))))
   `(marginalia-file-priv-exec ((t (:foreground ,s-operator))))
   `(marginalia-mode        ((t (:foreground ,s-statement))))
   `(marginalia-modified    ((t (:foreground ,s-constant))))
   `(marginalia-size        ((t (:foreground ,s-number))))
   `(marginalia-date        ((t (:foreground ,s-type))))

   `(which-key-key-face                 ((t (:foreground ,s-ident :weight bold))))
   `(which-key-group-description-face   ((t (:foreground ,s-keyword))))
   `(which-key-command-description-face ((t (:foreground ,s-fun))))
   `(which-key-local-map-description-face ((t (:foreground ,s-type))))
   `(which-key-separator-face           ((t (:foreground ,s-comment))))
   `(which-key-note-face                ((t (:foreground ,s-comment :slant italic))))
   `(which-key-posframe                 ((t (:background ,bg-float))))
   `(which-key-posframe-border          ((t (:background ,border))))

   `(company-tooltip                  ((t (:background ,bg-float :foreground ,fg))))
   `(company-tooltip-selection        ((t (:background ,bg-visual :weight bold))))
   `(company-tooltip-common           ((t (:foreground ,s-fun :weight bold))))
   `(company-tooltip-common-selection ((t (:foreground ,s-fun :weight bold))))
   `(company-tooltip-annotation       ((t (:foreground ,s-comment))))
   `(company-scrollbar-bg             ((t (:background ,bg-float))))
   `(company-scrollbar-fg             ((t (:background ,s-keyword))))
   `(company-preview                  ((t (:foreground ,fg-dim))))
   `(company-preview-common           ((t (:foreground ,s-fun))))
   `(company-preview-search           ((t (:background ,bg-search :foreground ,fg))))

   `(ivy-current-match                ((t (:background ,bg-visual :foreground ,fg :weight bold))))
   `(ivy-minibuffer-match-face-1      ((t (:foreground ,s-fun :weight bold))))
   `(ivy-minibuffer-match-face-2      ((t (:foreground ,s-string :weight bold))))
   `(ivy-minibuffer-match-face-3      ((t (:foreground ,s-type :weight bold))))
   `(ivy-minibuffer-match-face-4      ((t (:foreground ,s-constant :weight bold))))

   `(swiper-line-face                 ((t (:background ,bg-visual :weight bold))))
   `(swiper-match-face-1              ((t (:foreground ,s-ident :weight bold))))
   `(swiper-match-face-2              ((t (:foreground ,s-string :weight bold))))
   `(swiper-match-face-3              ((t (:foreground ,s-type :weight bold))))
   `(swiper-match-face-4              ((t (:foreground ,s-constant :weight bold))))

   ;; ----------------------------------------------------------------
   ;; Phase 8 — Polish
   ;; ----------------------------------------------------------------

   ;; magit
   `(magit-section-heading        ((t (:foreground ,s-keyword :weight bold))))
   `(magit-section-highlight      ((t (:background ,bg-m1 :extend t))))
   `(magit-section-heading-selection ((t (:foreground ,s-fun :weight bold))))
   `(magit-diff-added             ((t (:background ,diff-add-bg :foreground ,vcs-add :extend t))))
   `(magit-diff-added-highlight   ((t (:background ,diff-add-bg :foreground ,fg :extend t))))
   `(magit-diff-removed           ((t (:background ,diff-del-bg :foreground ,vcs-del :extend t))))
   `(magit-diff-removed-highlight ((t (:background ,diff-del-bg :foreground ,fg :extend t))))
   `(magit-diff-context           ((t (:foreground ,fg-dim :extend t))))
   `(magit-diff-context-highlight ((t (:background ,bg-m1 :foreground ,fg :extend t))))
   `(magit-diff-hunk-heading      ((t (:background ,bg-m1 :foreground ,s-keyword :extend t))))
   `(magit-diff-hunk-heading-highlight ((t (:background ,bg-p1 :foreground ,fg :extend t))))
   `(magit-diff-file-heading      ((t (:foreground ,s-fun :weight bold))))
   `(magit-diff-file-heading-highlight ((t (:background ,bg-m1 :foreground ,s-fun :weight bold))))
   `(magit-branch-current         ((t (:foreground ,s-type :weight bold :box t))))
   `(magit-branch-local           ((t (:foreground ,s-type))))
   `(magit-branch-remote          ((t (:foreground ,s-string))))
   `(magit-tag                    ((t (:foreground ,s-constant))))
   `(magit-hash                   ((t (:foreground ,s-comment))))
   `(magit-log-author             ((t (:foreground ,s-fun))))
   `(magit-log-date               ((t (:foreground ,fg-dim))))
   `(magit-process-ok             ((t (:foreground ,d-ok :weight bold))))
   `(magit-process-ng             ((t (:foreground ,d-error :weight bold))))
   `(magit-blame-heading          ((t (:background ,bg-m1 :foreground ,s-fun))))
   `(magit-blame-summary          ((t (:foreground ,fg))))
   `(magit-blame-date             ((t (:foreground ,fg-dim))))
   `(magit-blame-name             ((t (:foreground ,s-string))))
   `(magit-blame-hash             ((t (:foreground ,s-comment))))

   ;; LSP / lsp-ui
   `(lsp-face-semhl-class               ((t (:foreground ,s-type))))
   `(lsp-face-semhl-interface           ((t (:foreground ,s-type))))
   `(lsp-face-semhl-enum                ((t (:foreground ,s-type))))
   `(lsp-face-semhl-struct              ((t (:foreground ,s-type))))
   `(lsp-face-semhl-type                ((t (:foreground ,s-type))))
   `(lsp-face-semhl-type-parameter      ((t (:foreground ,s-type))))
   `(lsp-face-semhl-typeparameter       ((t (:foreground ,s-type))))
   `(lsp-face-semhl-namespace           ((t (:foreground ,s-type))))
   `(lsp-face-semhl-function            ((t (:foreground ,s-fun))))
   `(lsp-face-semhl-method              ((t (:foreground ,s-fun))))
   `(lsp-face-semhl-macro               ((t (:foreground ,s-preproc))))
   `(lsp-face-semhl-keyword             ((t (:foreground ,s-keyword :slant italic))))
   `(lsp-face-semhl-modifier            ((t (:foreground ,s-keyword :slant italic))))
   `(lsp-face-semhl-comment             ((t (:foreground ,s-comment :slant italic))))
   `(lsp-face-semhl-string              ((t (:foreground ,s-string))))
   `(lsp-face-semhl-number              ((t (:foreground ,s-number))))
   `(lsp-face-semhl-regexp              ((t (:foreground ,s-regex))))
   `(lsp-face-semhl-operator            ((t (:foreground ,s-operator))))
   `(lsp-face-semhl-constant            ((t (:foreground ,s-constant))))
   `(lsp-face-semhl-enum-member         ((t (:foreground ,s-constant))))
   `(lsp-face-semhl-enummember          ((t (:foreground ,s-constant))))
   `(lsp-face-semhl-property            ((t (:foreground ,s-ident))))
   `(lsp-face-semhl-member              ((t (:foreground ,s-ident))))
   `(lsp-face-semhl-parameter           ((t (:foreground ,s-param))))
   `(lsp-face-semhl-variable            ((t (:foreground ,s-ident))))

   ;; LSP Modifiers (must be explicitly unspecified so they don't override base token colors
   ;; by inheriting from standard font-lock faces)
   `(lsp-face-semhl-definition          ((t (:inherit unspecified))))
   `(lsp-face-semhl-declaration         ((t (:inherit unspecified))))
   `(lsp-face-semhl-implementation      ((t (:inherit unspecified))))
   `(lsp-face-semhl-default-library     ((t (:inherit unspecified))))
   `(lsp-face-semhl-static              ((t (:inherit unspecified))))
   `(lsp-face-semhl-readonly            ((t (:inherit unspecified))))
   `(lsp-face-semhl-deprecated          ((t (:strike-through t))))

   `(lsp-face-highlight-textual   ((t (:background ,bg-p1))))
   `(lsp-face-highlight-read      ((t (:background ,bg-p1 :foreground ,s-string))))
   `(lsp-face-highlight-write     ((t (:background ,bg-p1 :foreground ,s-constant))))
   `(lsp-headerline-breadcrumb-path-face ((t (:foreground ,fg-dim))))
   `(lsp-headerline-breadcrumb-path-error-face   ((t (:underline (:color ,d-error :style wave) :foreground ,fg-dim))))
   `(lsp-headerline-breadcrumb-path-warning-face ((t (:underline (:color ,d-warn :style wave) :foreground ,fg-dim))))
   `(lsp-headerline-breadcrumb-path-info-face    ((t (:foreground ,fg-dim))))
   `(lsp-headerline-breadcrumb-path-hint-face    ((t (:foreground ,fg-dim))))
   `(lsp-headerline-breadcrumb-symbols-face      ((t (:foreground ,s-fun :weight bold))))
   `(lsp-ui-doc-background        ((t (:background ,bg-float))))
   `(lsp-ui-doc-header            ((t (:background ,bg-float :foreground ,s-keyword :weight bold))))
   `(lsp-ui-doc-border            ((t (:background ,border))))
   `(lsp-ui-peek-filename         ((t (:foreground ,s-type))))
   `(lsp-ui-peek-header           ((t (:background ,bg-m1 :foreground ,s-keyword :weight bold))))
   `(lsp-ui-peek-highlight        ((t (:background ,bg-search :foreground ,fg))))
   `(lsp-ui-peek-line-number      ((t (:foreground ,fg-dim))))
   `(lsp-ui-peek-list             ((t (:background ,bg-m1))))
   `(lsp-ui-peek-peek             ((t (:background ,bg-m1))))
   `(lsp-ui-peek-selection        ((t (:background ,bg-visual :weight bold))))
   `(lsp-ui-sideline-code-action  ((t (:foreground ,s-constant))))
   `(lsp-ui-sideline-current-symbol ((t (:foreground ,s-statement :weight bold))))
   `(lsp-ui-sideline-symbol       ((t (:foreground ,s-special1))))

   ;; flycheck / flymake
   `(flycheck-error               ((t (:underline (:color ,d-error :style wave)))))
   `(flycheck-warning             ((t (:underline (:color ,d-warn :style wave)))))
   `(flycheck-info                ((t (:underline (:color ,d-info :style wave)))))
   `(flycheck-fringe-error        ((t (:foreground ,d-error))))
   `(flycheck-fringe-warning      ((t (:foreground ,d-warn))))
   `(flycheck-fringe-info         ((t (:foreground ,d-info))))
   `(flycheck-error-list-error    ((t (:foreground ,d-error :weight bold))))
   `(flycheck-error-list-warning  ((t (:foreground ,d-warn :weight bold))))
   `(flycheck-error-list-info     ((t (:foreground ,d-info :weight bold))))
   `(flymake-error                ((t (:underline (:color ,d-error :style wave)))))
   `(flymake-warning              ((t (:underline (:color ,d-warn :style wave)))))
   `(flymake-note                 ((t (:underline (:color ,d-info :style wave)))))

   ;; evil
   `(evil-ex-info                 ((t (:foreground ,s-fun))))
   `(evil-ex-substitute-matches   ((t (:background ,diff-del-bg :foreground ,vcs-del :weight bold))))
   `(evil-ex-substitute-replacement ((t (:background ,diff-add-bg :foreground ,vcs-add :weight bold))))
   `(evil-ex-lazy-highlight       ((t (:background ,bg-search :foreground ,fg))))
   `(evil-ex-search               ((t (:background ,bg-search :foreground ,fg :weight bold))))

   ;; rainbow-delimiters
   `(rainbow-delimiters-depth-1-face ((t (:foreground ,s-keyword))))
   `(rainbow-delimiters-depth-2-face ((t (:foreground ,s-fun))))
   `(rainbow-delimiters-depth-3-face ((t (:foreground ,s-type))))
   `(rainbow-delimiters-depth-4-face ((t (:foreground ,s-string))))
   `(rainbow-delimiters-depth-5-face ((t (:foreground ,s-ident))))
   `(rainbow-delimiters-depth-6-face ((t (:foreground ,s-constant))))
   `(rainbow-delimiters-depth-7-face ((t (:foreground ,s-number))))
   `(rainbow-delimiters-depth-8-face ((t (:foreground ,s-operator))))
   `(rainbow-delimiters-depth-9-face ((t (:foreground ,s-special1))))
   `(rainbow-delimiters-mismatched-face ((t (:foreground ,d-error :weight bold))))
   `(rainbow-delimiters-unmatched-face  ((t (:foreground ,d-error :weight bold))))

   ;; hl-todo
   `(hl-todo                ((t (:foreground ,s-constant :weight bold))))

   ;; dired
   `(dired-directory        ((t (:foreground ,s-fun :weight bold))))
   `(dired-symlink          ((t (:foreground ,s-special1 :slant italic))))
   `(dired-broken-symlink   ((t (:foreground ,d-error :slant italic))))
   `(dired-header           ((t (:foreground ,s-keyword :weight bold))))
   `(dired-mark             ((t (:foreground ,s-constant :weight bold))))
   `(dired-marked           ((t (:foreground ,s-constant :weight bold))))
   `(dired-flagged          ((t (:foreground ,d-error :weight bold))))
   `(dired-perm-write       ((t (:foreground ,s-constant))))
   `(dired-ignored          ((t (:foreground ,fg-dim))))

   ;; eshell / term / vterm — ANSI-mapped
   `(ansi-color-black            ((t (:foreground ,ansi-black :background ,ansi-black))))
   `(ansi-color-red              ((t (:foreground ,ansi-red))))
   `(ansi-color-green            ((t (:foreground ,ansi-green))))
   `(ansi-color-yellow           ((t (:foreground ,ansi-yellow))))
   `(ansi-color-blue             ((t (:foreground ,ansi-blue))))
   `(ansi-color-magenta          ((t (:foreground ,ansi-magenta))))
   `(ansi-color-cyan             ((t (:foreground ,ansi-cyan))))
   `(ansi-color-white            ((t (:foreground ,ansi-white))))
   `(ansi-color-bright-black     ((t (:foreground ,ansi-bright-black))))
   `(ansi-color-bright-red       ((t (:foreground ,ansi-bright-red))))
   `(ansi-color-bright-green     ((t (:foreground ,ansi-bright-green))))
   `(ansi-color-bright-yellow    ((t (:foreground ,ansi-bright-yellow))))
   `(ansi-color-bright-blue      ((t (:foreground ,ansi-bright-blue))))
   `(ansi-color-bright-magenta   ((t (:foreground ,ansi-bright-magenta))))
   `(ansi-color-bright-cyan      ((t (:foreground ,ansi-bright-cyan))))
   `(ansi-color-bright-white     ((t (:foreground ,ansi-bright-white))))

   `(term-color-black            ((t (:foreground ,ansi-black :background ,ansi-black))))
   `(term-color-red              ((t (:foreground ,ansi-red))))
   `(term-color-green            ((t (:foreground ,ansi-green))))
   `(term-color-yellow           ((t (:foreground ,ansi-yellow))))
   `(term-color-blue             ((t (:foreground ,ansi-blue))))
   `(term-color-magenta          ((t (:foreground ,ansi-magenta))))
   `(term-color-cyan             ((t (:foreground ,ansi-cyan))))
   `(term-color-white            ((t (:foreground ,ansi-white))))
   `(term-color-bright-black     ((t (:foreground ,ansi-bright-black))))
   `(term-color-bright-red       ((t (:foreground ,ansi-bright-red))))
   `(term-color-bright-green     ((t (:foreground ,ansi-bright-green))))
   `(term-color-bright-yellow    ((t (:foreground ,ansi-bright-yellow))))
   `(term-color-bright-blue      ((t (:foreground ,ansi-bright-blue))))
   `(term-color-bright-magenta   ((t (:foreground ,ansi-bright-magenta))))
   `(term-color-bright-cyan      ((t (:foreground ,ansi-bright-cyan))))
   `(term-color-bright-white     ((t (:foreground ,ansi-bright-white))))

   `(vterm-color-default         ((t (:background ,bg :foreground ,fg))))
   `(vterm-color-black           ((t (:foreground ,ansi-black :background ,ansi-black))))
   `(vterm-color-red             ((t (:foreground ,ansi-red :background ,ansi-red))))
   `(vterm-color-green           ((t (:foreground ,ansi-green :background ,ansi-green))))
   `(vterm-color-yellow          ((t (:foreground ,ansi-yellow :background ,ansi-yellow))))
   `(vterm-color-blue            ((t (:foreground ,ansi-blue :background ,ansi-blue))))
   `(vterm-color-magenta         ((t (:foreground ,ansi-magenta :background ,ansi-magenta))))
   `(vterm-color-cyan            ((t (:foreground ,ansi-cyan :background ,ansi-cyan))))
   `(vterm-color-white           ((t (:foreground ,ansi-white :background ,ansi-white))))

   ;; Customize the diagnostics number-on-modeline strip used by Doom
   `(flycheck-posframe-background-face ((t (:background ,bg-float))))
   `(flycheck-posframe-error-face      ((t (:background ,bg-float :foreground ,d-error))))
   `(flycheck-posframe-warning-face    ((t (:background ,bg-float :foreground ,d-warn))))
   `(flycheck-posframe-info-face       ((t (:background ,bg-float :foreground ,d-info))))
   ))

;;;###autoload
(when (and (boundp 'custom-theme-load-path) load-file-name)
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'kanagawa-dragon-nvim)

;;; kanagawa-dragon-nvim-theme.el ends here
